### ISSUE TITLE
🚀 Feature: Improve EnvisEdge code base for better usability

### ISSUE THREAD

**Issue by ramesht007** [NimbleEdge/EnvisEdge#183]
### 🔖 Feature description

- [ ] Add modules and submodules for make the  training jobs running.
- [ ] Add new models for that support federated leaning tasks.
- [ ] Add new federated learning datasets.
- [ ] improve the serialization and deserialization in the data models.
- [ ] Fix the readme with latest commands to run the code.

### 🎤 Pitch

Current code is not fully functional we need to improve the code base and different functionalities to make the codebase running.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/NimbleEdge/EnvisEdge/blob/main/CODE_OF_CONDUCT.md)
